### PR TITLE
Fix behavior of DitheringMode with QVariant in Qt5

### LINKED ISSUE #3304: RemoteSync issues with Qt5
### Expected Behaviour

Stable Connection

### Actual Behaviour

During first connection, connection fails at StelCore.ditheringMode and refuses to connect

### Steps to reproduce

Run Qt5-based build

It seems the enum DitheringMode is not properly registered in the meta system.  Qt6 makes this easier, there we have no more issue (after #3303).

### System
* Stellarium version: 23.2-qt5
* Operating system: Win11
* Graphics Card: irrelevant

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

### PR DESCRIPTION
**Pull request by 10110111**
Fixes #3304

I didn't quite understand how `DitheringMode` gets into `QVariant` via the RemoteSync plugin, but at least with this change `QVariant::fromValue(DitheringMode::Color888).toString()` yields the correct string. Before this change the output string was empty. So I suppose this should be sufficient for #3304.

### CODE REVIEW

**Comment by 10110111** [comment]
Should work now.

**Comment by gzotti** [comment]
Ah yes, there!
Hmm, did you compile with Qt5? An operator `>>` is missing.

**Comment by 10110111** [comment]
Compiled with Qt 5.15 successfully. What is your error message?

**Comment by gzotti** [comment]
Ah yes, it works on 5.15.2. 

Previously I tried 5.12.12 which we usually need. Sorry, MSVC has German compiler output:

C:\Qt\5.12.12\msvc2017_64\include\QtCore/qmetatype.h(815): error C2679: Bin„rer Operator ">>": Es konnte kein Operator gefunden werden, der einen rechtsseitigen Operanden vom Typ "T" akzeptiert (oder keine geeignete Konvertierung m”glich)
        with
        [
            T=DitheringMode
        ]
C:\Qt\5.12.12\msvc2017_64\include\QtCore/qdatastream.h(164): note: kann "QDataStream &QDataStream::operator >>(char *&)" sein
C:\Qt\5.12.12\msvc2017_64\include\QtCore/qdatastream.h(163): note: oder "QDataStream &QDataStream::operator >>(double &)"
C:\Qt\5.12.12\msvc2017_64\include\QtCore/qdatastream.h(162): note: oder "QDataStream &QDataStream::operator >>(float &)"
C:\Qt\5.12.12\msvc2017_64\include\QtCore/qdatastream.h(161): note: oder "QDataStream &QDataStream::operator >>(qfloat16 &)"
C:\Qt\5.12.12\msvc2017_64\include\QtCore/qdatastream.h(160): note: oder "QDataStream &QDataStream::operator >>(bool &)"
C:\Qt\5.12.12\msvc2017_64\include\QtCore/qdatastream.h(158): note: oder "QDataStream &QDataStream::operator >>(std::nullptr_t &)"
C:\Qt\5.12.12\msvc2017_64\include\QtCore/qdatastream.h(352): note: oder "QDataStream &QDataStream::operator >>(quint64 &)"
C:\Qt\5.12.12\msvc2017_64\include\QtCore/qdatastream.h(156): note: oder "QDataStream &QDataStream::operator >>(qint64 &)"
C:\Qt\5.12.12\msvc2017_64\include\QtCore/qdatastream.h(349): note: oder "QDataStream &QDataStream::operator >>(quint32 &)"
C:\Qt\5.12.12\msvc2017_64\include\QtCore/qdatastream.h(154): note: oder "QDataStream &QDataStream::operator >>(qint32 &)"
C:\Qt\5.12.12\msvc2017_64\include\QtCore/qdatastream.h(346): note: oder "QDataStream &QDataStream::operator >>(quint16 &)"
C:\Qt\5.12.12\msvc2017_64\include\QtCore/qdatastream.h(152): note: oder "QDataStream &QDataStream::operator >>(qint16 &)"
C:\Qt\5.12.12\msvc2017_64\include\QtCore/qdatastream.h(343): note: oder "QDataStream &QDataStream::operator >>(quint8 &)"
C:\Qt\5.12.12\msvc2017_64\include\QtCore/qdatastream.h(150): note: oder "QDataStream &QDataStream::operator >>(qint8 &)"
C:\Qt\5.12.12\msvc2017_64\include\QtCore\qtimezone.h(181): note: oder "QDataStream &operator >>(QDataStream &,QTimeZone &)"
C:\Qt\5.12.12\msvc2017_64\include\QtWidgets/qsizepolicy.h(174): note: oder "QDataStream &operator >>(QDataStream &,QSizePolicy &)"
C:\Qt\5.12.12\msvc2017_64\include\QtGui/qpalette.h(208): note: oder "QDataStream &operator >>(QDataStream &,QPalette &)"
C:\Qt\5.12.12\msvc2017_64\include\QtGui/qpen.h(57): note: oder "QDataStream &operator >>(QDataStream &,QPen &)"
C:\Qt\5.12.12\msvc2017_64\include\QtGui/qbrush.h(145): note: oder "QDataStream &operator >>(QDataStream &,QBrush &)"
C:\Qt\5.12.12\msvc2017_64\include\QtGui/qpixmap.h(194): note: oder "QDataStream &operator >>(QDataStream &,QPixmap &)"
C:\Qt\5.12.12\msvc2017_64\include\QtPositioning\qgeopositioninfo.h(108): note: oder "QDataStream &operator >>(QDataStream &,QGeoPositionInfo::Attribute &)"
C:\Qt\5.12.12\msvc2017_64\include\QtPositioning\qgeopositioninfo.h(96): note: oder "QDataStream &operator >>(QDataStream &,QGeoPositionInfo &)"
C:\Qt\5.12.12\msvc2017_64\include\QtPositioning\qgeocoordinate.h(129): note: oder "QDataStream &operator >>(QDataStream &,QGeoCoordinate &)"
C:\Qt\5.12.12\msvc2017_64\include\QtGui/qvector2d.h(282): note: oder "QDataStream &operator >>(QDataStream &,QVector2D &)"
C:\Qt\5.12.12\msvc2017_64\include\QtCore/qurl.h(411): note: oder "QDataStream &operator >>(QDataStream &,QUrl &)"
C:\Qt\5.12.12\msvc2017_64\include\QtGui/qkeysequence.h(59): note: oder "QDataStream &operator >>(QDataStream &,QKeySequence &)"
C:\Qt\5.12.12\msvc2017_64\include\QtGui\qcursor.h(128): note: oder "QDataStream &operator >>(QDataStream &,QCursor &)"
C:\Qt\5.12.12\msvc2017_64\include\QtCore/qeasingcurve.h(125): note: oder "QDataStream &operator >>(QDataStream &,QEasingCurve &)"
C:\Qt\5.12.12\msvc2017_64\include\QtCore\qdatetime.h(386): note: oder "QDataStream &operator >>(QDataStream &,QDateTime &)"
C:\Qt\5.12.12\msvc2017_64\include\QtCore\qdatetime.h(213): note: oder "QDataStream &operator >>(QDataStream &,QTime &)"
C:\Qt\5.12.12\msvc2017_64\include\QtCore\qdatetime.h(149): note: oder "QDataStream &operator >>(QDataStream &,QDate &)"
C:\Qt\5.12.12\msvc2017_64\include\QtGui/qfont.h(326): note: oder "QDataStream &operator >>(QDataStream &,QFont &)"
C:\Qt\5.12.12\msvc2017_64\include\QtGui\qimage.h(491): note: oder "QDataStream &operator >>(QDataStream &,QImage &)"
C:\Qt\5.12.12\msvc2017_64\include\QtGui/qtransform.h(374): note: oder "QDataStream &operator >>(QDataStream &,QTransform &)"
C:\Qt\5.12.12\msvc2017_64\include\QtGui/qpainterpath.h(230): note: oder "QDataStream &operator >>(QDataStream &,QPainterPath &)"
C:\Qt\5.12.12\msvc2017_64\include\QtGui/qmatrix.h(185): note: oder "QDataStream &operator >>(QDataStream &,QMatrix &)"
C:\Qt\5.12.12\msvc2017_64\include\QtCore/qline.h(431): note: oder "QDataStream &operator >>(QDataStream &,QLineF &)"
C:\Qt\5.12.12\msvc2017_64\include\QtCore/qline.h(208): note: oder "QDataStream &operator >>(QDataStream &,QLine &)"
C:\Qt\5.12.12\msvc2017_64\include\QtGui/qregion.h(163): note: oder "QDataStream &operator >>(QDataStream &,QRegion &)"
C:\Qt\5.12.12\msvc2017_64\include\QtGui/qpolygon.h(196): note: oder "QDataStream &operator >>(QDataStream &,QPolygonF &)"
C:\Qt\5.12.12\msvc2017_64\include\QtGui/qpolygon.h(117): note: oder "QDataStream &operator >>(QDataStream &,QPolygon &)"
D:\StelDev\GIT\stellarium\src\core\StelLocation.hpp(153): note: oder "QDataStream &operator >>(QDataStream &,StelLocation &)"
D:\StelDev\GIT\stellarium\src\core\StelSphereGeometry.hpp(133): note: oder "QDataStream &operator >>(QDataStream &,SphericalRegionP &)"
D:\StelDev\GIT\stellarium\src\core\OctahedronPolygon.hpp(116): note: oder "QDataStream &operator >>(QDataStream &,OctahedronPolygon &)"
D:\StelDev\GIT\stellarium\src\core\OctahedronPolygon.hpp(46): note: oder "QDataStream &operator >>(QDataStream &,EdgeVertex &)"
D:\StelDev\GIT\stellarium\src\core\StelVertexArray.hpp(108): note: oder "QDataStream &operator >>(QDataStream &,StelVertexArray &)"
C:\Qt\5.12.12\msvc2017_64\include\QtCore\qregularexpression.h(172): note: oder "QDataStream &operator >>(QDataStream &,QRegularExpression &)"
C:\Qt\5.12.12\msvc2017_64\include\QtGui\qcolor.h(61): note: oder "QDataStream &operator >>(QDataStream &,QColor &)"
C:\Qt\5.12.12\msvc2017_64\include\QtGui\qmatrix4x4.h(1108): note: oder "QDataStream &operator >>(QDataStream &,QMatrix4x4 &)"
C:\Qt\5.12.12\msvc2017_64\include\QtCore/qrect.h(637): note: oder "QDataStream &operator >>(QDataStream &,QRectF &)"
C:\Qt\5.12.12\msvc2017_64\include\QtCore/qrect.h(177): note: oder "QDataStream &operator >>(QDataStream &,QRect &)"
C:\Qt\5.12.12\msvc2017_64\include\QtCore/qsize.h(277): note: oder "QDataStream &operator >>(QDataStream &,QSizeF &)"
C:\Qt\5.12.12\msvc2017_64\include\QtCore/qsize.h(109): note: oder "QDataStream &operator >>(QDataStream &,QSize &)"
C:\Qt\5.12.12\msvc2017_64\include\QtCore/qmargins.h(328): note: oder "QDataStream &operator >>(QDataStream &,QMarginsF &)"
C:\Qt\5.12.12\msvc2017_64\include\QtCore/qmargins.h(95): note: oder "QDataStream &operator >>(QDataStream &,QMargins &)"
C:\Qt\5.12.12\msvc2017_64\include\QtGui/qquaternion.h(399): note: oder "QDataStream &operator >>(QDataStream &,QQuaternion &)"
C:\Qt\5.12.12\msvc2017_64\include\QtCore/qtextstream.h(227): note: oder "QTextStream &operator >>(QTextStream &,QTextStreamFunction)"
C:\Qt\5.12.12\msvc2017_64\include\QtCore/qlocale.h(1123): note: oder "QDataStream &operator >>(QDataStream &,QLocale &)"
C:\Qt\5.12.12\msvc2017_64\include\QtCore/qvariant.h(564): note: oder "QDataStream &operator >>(QDataStream &,QVariant::Type &)"
C:\Qt\5.12.12\msvc2017_64\include\QtCore/qvariant.h(562): note: oder "QDataStream &operator >>(QDataStream &,QVariant &)"
C:\Qt\5.12.12\msvc2017_64\include\QtCore/qregexp.h(125): note: oder "QDataStream &operator >>(QDataStream &,QRegExp &)"
C:\Qt\5.12.12\msvc2017_64\include\QtGui/qvector4d.h(310): note: oder "QDataStream &operator >>(QDataStream &,QVector4D &)"
C:\Qt\5.12.12\msvc2017_64\include\QtGui/qvector3d.h(309): note: oder "QDataStream &operator >>(QDataStream &,QVector3D &)"
C:\Qt\5.12.12\msvc2017_64\include\QtCore/qpoint.h(278): note: oder "QDataStream &operator >>(QDataStream &,QPointF &)"
C:\Qt\5.12.12\msvc2017_64\include\QtCore/qpoint.h(113): note: oder "QDataStream &operator >>(QDataStream &,QPoint &)"
C:\Qt\5.12.12\msvc2017_64\include\QtCore\qstring.h(1416): note: oder "QDataStream &operator >>(QDataStream &,QString &)"
C:\Qt\5.12.12\msvc2017_64\include\QtCore/qbytearray.h(696): note: oder "QDataStream &operator >>(QDataStream &,QByteArray &)"
C:\Qt\5.12.12\msvc2017_64\include\QtCore/qchar.h(626): note: oder "QDataStream &operator >>(QDataStream &,QChar &)"
C:\Qt\5.12.12\msvc2017_64\include\QtCore/qmetatype.h(815): note: bei Anpassung der Argumentliste "(QDataStream, T)"
        with
        [
            T=DitheringMode
        ]
C:\Qt\5.12.12\msvc2017_64\include\QtCore/qmetatype.h(814): note: beim Kompilieren der Klasse Vorlage-Memberfunktion "void QtMetaTypePrivate::QMetaTypeFunctionHelper<T,true>::Load(QDataStream &,void *)"
        with
        [
            T=DitheringMode
        ]
C:\Qt\5.12.12\msvc2017_64\include\QtCore/qmetatype.h(1920): note: Siehe Verweis auf die gerade kompilierte Instanziierung "void QtMetaTypePrivate::QMetaTypeFunctionHelper<T,true>::Load(QDataStream &,void *)" der Funktions-Vorlage.
        with
        [
            T=DitheringMode
        ]
C:\Qt\5.12.12\msvc2017_64\include\QtCore/qmetatype.h(1920): note: Siehe Verweis auf die gerade kompilierte Klasse Vorlage-Instanziierung "QtMetaTypePrivate::QMetaTypeFunctionHelper<T,true>".
        with
        [
            T=DitheringMode
        ]
D:\StelDev\GIT\stellarium\src\core\StelCore.cpp(2076): note: Siehe Verweis auf die gerade kompilierte Instanziierung "int qRegisterMetaTypeStreamOperators<DitheringMode>(void)" der Funktions-Vorlage.
[210/368 7.8/sec] Building CXX object src\CMakeFiles\stelMain.dir\core\MultiLevelJsonBase.cpp.obj
[211/368 7.9/sec] Building CXX object src\CMakeFiles\stelMain.dir\core\StelVideoMgr.cpp.obj
[212/368 7.9/sec] Building CXX object src\CMakeFiles\stelMain.dir\core\StelSkyDrawer.cpp.obj
[213/368 7.9/sec] Building CXX object src\CMakeFiles\stelMain.dir\core\StelPainter.cpp.obj
[214/368 7.9/sec] Building CXX object src\CMakeFiles\stelMain.dir\core\StelSkyImageTile.cpp.obj
[215/368 7.9/sec] Building CXX object src\CMakeFiles\stelMain.dir\core\StelLocationMgr.cpp.obj
[216/368 7.8/sec] Building CXX object src\CMakeFiles\stelMain.dir\core\StelObjectModule.cpp.obj
[217/368 7.8/sec] Building CXX object src\CMakeFiles\stelMain.dir\core\StelOpenGL.cpp.obj
[218/368 7.8/sec] Building CXX object src\CMakeFiles\stelMain.dir\core\StelLocaleMgr.cpp.obj
[219/368 7.8/sec] Building CXX object src\CMakeFiles\stelMain.dir\core\StelToneReproducer.cpp.obj
[220/368 7.8/sec] Building CXX object src\CMakeFiles\stelMain.dir\core\StelIniParser.cpp.obj
[221/368 7.8/sec] Building CXX object src\CMakeFiles\stelMain.dir\core\StelApp.cpp.obj
[222/368 7.9/sec] Building CXX object src\CMakeFiles\stelMain.dir\core\StelObject.cpp.obj
[223/368 7.9/sec] Building CXX object src\CMakeFiles\stelMain.dir\core\StelModuleMgr.cpp.obj
[224/368 7.9/sec] Building CXX object src\CMakeFiles\stelMain.dir\core\StelSkyCultureMgr.cpp.obj
[225/368 7.9/sec] Building CXX object src\CMakeFiles\stelMain.dir\core\StelObjectMgr.cpp.obj
[226/368 7.9/sec] Building CXX object src\CMakeFiles\stelMain.dir\core\StelTextureMgr.cpp.obj
[227/368 7.9/sec] Building CXX object src\CMakeFiles\stelMain.dir\core\StelSkyLayer.cpp.obj
[228/368 7.9/sec] Building CXX object src\CMakeFiles\stelMain.dir\core\OctahedronPolygon.cpp.obj
[229/368 7.8/sec] Building CXX object src\CMakeFiles\stelMain.dir\core\StelTexture.cpp.obj
[230/368 7.8/sec] Building CXX object src\CMakeFiles\stelMain.dir\stelMain_autogen\mocs_compilation.cpp.obj
ninja: build stopped: subcommand failed.
12:05:36: Der Prozess "C:\Qt\Tools\CMake_64\bin\cmake.exe" wurde mit dem Rückgabewert 1 beendet.
Fehler beim Erstellen/Deployment des Projekts Stellarium (Kit: Desktop Qt 5.12.12 MSVC2017 64bit)
Bei der Ausführung von Schritt "Erstellen"
12:05:36: Verstrichene Zeit: 00:30.

**Comment by gzotti** [comment]
We could move to Qt5.15 on Windows of course. However, I don't know about Linux practice, are Qt5.15 packages easily available everywhere? Ubuntu 20.4LTS? Arch? Mandriva? RaspberryOS? Or whatever you are using? Small Linux SBCs make nice client screens.

**Comment by 10110111** [comment]
OK, the new version should support Qt 5.12 too.

**Review by gzotti — APPROVED** [review]
Yay! Many thanks!
