### ISSUE TITLE
Not compatible with INDI 2.1.0 version

### ISSUE THREAD

**Issue by AstroAir** [Stellarium/stellarium#3979]
When I tried to build in Ubuntu 22.04 (WSN) according to the tutorial, an error occurred, mainly due to incompatibility with the INDI client. The specific error is as follows:

```txt
In file included from /home/max/Lithium/test/libs/stellarium-24.3/plugins/TelescopeControl/src/INDI/TelescopeClientINDI.hpp:24,
                 from /home/max/Lithium/test/libs/stellarium-24.3/plugins/TelescopeControl/src/INDI/TelescopeClientINDI.cpp:19:
/home/max/Lithium/test/libs/stellarium-24.3/plugins/TelescopeControl/src/INDI/INDIConnection.hpp:72:14: error ‘void INDIConnection::newDevice(INDI::BaseDevice*)’ marked ‘override’, but does not override
   72 |         void newDevice(INDI::BaseDevice *dp) override;
      |              ^~~~~~~~~
/home/max/Lithium/test/libs/stellarium-24.3/plugins/TelescopeControl/src/INDI/INDIConnection.hpp:73:14: error ‘void INDIConnection::removeDevice(INDI::BaseDevice*)’ marked ‘override’, but does not override
   73 |         void removeDevice(INDI::BaseDevice *dp) override;
      |              ^~~~~~~~~~~~
/home/max/Lithium/test/libs/stellarium-24.3/plugins/TelescopeControl/src/INDI/INDIConnection.hpp:74:14: error ‘void INDIConnection::newProperty(INDI::Property*)’ marked ‘override’, but does not override
   74 |         void newProperty(INDI::Property *property) override;
      |              ^~~~~~~~~~~
/home/max/Lithium/test/libs/stellarium-24.3/plugins/TelescopeControl/src/INDI/INDIConnection.hpp:75:14: error ‘void INDIConnection::removeProperty(INDI::Property*)’ marked ‘override’, but does not override
   75 |         void removeProperty(INDI::Property *property) override;
      |              ^~~~~~~~~~~~~~
/home/max/Lithium/test/libs/stellarium-24.3/plugins/TelescopeControl/src/INDI/INDIConnection.hpp:76:14: error ‘void INDIConnection::newBLOB(IBLOB*)’ marked ‘override’, but does not override
   76 |         void newBLOB(IBLOB *bp) override;
      |              ^~~~~~~
/home/max/Lithium/test/libs/stellarium-24.3/plugins/TelescopeControl/src/INDI/INDIConnection.hpp:77:14: error ‘void INDIConnection::newSwitch(ISwitchVectorProperty*)’ marked ‘override’, but does not override
   77 |         void newSwitch(ISwitchVectorProperty *svp) override;
      |              ^~~~~~~~~
/home/max/Lithium/test/libs/stellarium-24.3/plugins/TelescopeControl/src/INDI/INDIConnection.hpp:78:14: error ‘void INDIConnection::newNumber(INumberVectorProperty*)’ marked ‘override’, but does not override
   78 |         void newNumber(INumberVectorProperty *nvp) override;
      |              ^~~~~~~~~
/home/max/Lithium/test/libs/stellarium-24.3/plugins/TelescopeControl/src/INDI/INDIConnection.hpp:79:14: error ‘void INDIConnection::newText(ITextVectorProperty*)’ marked ‘override’, but does not override
   79 |         void newText(ITextVectorProperty *tvp) override;
      |              ^~~~~~~
/home/max/Lithium/test/libs/stellarium-24.3/plugins/TelescopeControl/src/INDI/INDIConnection.hpp:80:14: error ‘void INDIConnection::newLight(ILightVectorProperty*)’ marked ‘override’, but does not override
   80 |         void newLight(ILightVectorProperty *lvp) override;
      |              ^~~~~~~~
/home/max/Lithium/test/libs/stellarium-24.3/plugins/TelescopeControl/src/INDI/INDIConnection.hpp:81:14: error ‘void INDIConnection::newMessage(INDI::BaseDevice*, int)’ marked ‘override’, but does not override
   81 |         void newMessage(INDI::BaseDevice *dp, int messageID) override;
      |              ^~~~~~~~~~
```

GCC Version: 11.4.0
INDI Version: 2.1.0

**Comment by alex-w** [comment]
Fixed in master (PR #3269)
