### ISSUE TITLE
Build is broken with gpsd-3.19

### ISSUE THREAD

**Issue by bkuhls** [Stellarium/stellarium#733]
### Expected Behaviour
Successful build with gpsd-3.19

### Actual Behaviour
Build is broken with gpsd-3.19 due to upstream changes
https://gitlab.com/gpsd/gpsd/commit/259196e2ece002ff63a0da1831a90e6c0b74ea7f
https://gitlab.com/gpsd/gpsd/commit/af1104274a405f97095caa0897b236d6c913f171

Removing this line "fixes" the build
https://github.com/Stellarium/stellarium/blob/master/src/core/StelLocationMgr.cpp#L166

### Steps to reproduce
Build with gpsd-3.19

### System
* Stellarium version: 0.19.1
* Operating system: Linux

### Logfile 
/home/buildroot/br6/output/build/stellarium-0.19.1/src/core/StelLocationMgr.cpp: In member function ‘virtual void LibGPSLookupHelper::query()’:
/home/buildroot/br6/output/build/stellarium-0.19.1/src/core/StelLocationMgr.cpp:166:63: error: ‘struct gps_data_t’ has no member named ‘epe’
     qDebug() << "Spherical Position Error (epe):" << newdata->epe;

**Comment by gzotti** [comment]
Thanks for notifying. However the line should not be removed but changed into newdata->sep, but this would then break linking to and running with older versions of gpsd. Is there any gpsd API that can be used instead?

**Comment by bkuhls** [comment]
> However the line should not be removed but changed into newdata->sep

This causes another build error:
```
/home/buildroot/br6/output/build/stellarium-0.19.1/src/core/StelLocationMgr.cpp:166:63: error: ‘struct gps_data_t’ has no member named ‘sep’; did you mean ‘set’?
     qDebug() << "Spherical Position Error (epe):" << newdata->sep;
```
> Is there any gpsd API that can be used instead?

Sorry, no idea.

**Comment by bkuhls** [comment]
I can confirm that this fix solves the build error:
https://git.archlinux.org/svntogit/packages.git/tree/trunk/stellarium-gpsd-3.19.patch?h=packages/stellarium

gpsd-3.19 contains GPSD_API_MAJOR_VERSION 8, so something like
```
#if GPSD_API_MAJOR_VERSION >= 8
```
should be backwards compatible.

**Comment by alex-w** [comment]
Please check this patch: https://github.com/Stellarium/stellarium/commit/ce26d740db94a2ee4e88595cba0ea9c4cbde2dcb

**Comment by bkuhls** [comment]
> Please check this patch: [ce26d74](https://github.com/Stellarium/stellarium/commit/ce26d740db94a2ee4e88595cba0ea9c4cbde2dcb)

Build is still broken:
```
/home/buildroot/br6/output/build/stellarium-0.19.1/src/core/StelLocationMgr.cpp:171:63: error: ‘struct gps_data_t’ has no member named ‘sep’; did you mean ‘set’?
     qDebug() << "Spherical Position Error (sep):" << newdata->sep;
```
We need "newdata->fix.sep" according to the alpine linux patch, only with this change the build error is solved.

**Comment by alex-w** [comment]
It's a strange, but thanks for testing: https://github.com/Stellarium/stellarium/commit/29336f899dec12d7583efb513e1477d4cfc9a621

**Comment by bkuhls** [comment]
Thanks, bug is solved.
Just sent a patch upstream to include stellarium into [buildroot](http://buildroot.uclibc.org/): http://patchwork.ozlabs.org/patch/1141792/

**Comment by gzotti** [comment]
The compile-time flag is no good solution. There should be a version-independent API. Or when will Ubuntu, Fedora, Debian, RedHat, Scientific Linux, CentOS, ... switch to a new version of gpsd? Then Stellarium needs to be recompiled as well.  Better comment out this line for now, and then let's find a clean solution.

**Comment by alex-w** [comment]
>There should be a version-independent API.

In possible through introducing API for API :-/

**Comment by gzotti** [comment]
Just checking if/how gpsd data can be read from the JSON stream.

**Comment by gzotti** [comment]
No way. It's just a comment. Leave it commented away until all OS use newer gpsd.
