### ISSUE TITLE
macOS broken build due to arm64 on Intel Mac

### ISSUE THREAD

**Issue by unpacklo** [Stellarium/stellarium#2550]
I noticed master has become broken on my macOS machine, but I can't tell if this is a local configuration problem or something actually wrong in the repo. Have I done something wrong?

This is the first error I encounter:

```
In file included from /Users/dale/code/stellarium/src/external/qtcompress/qzip.cpp:46:
In file included from /Users/dale/code/stellarium/src/external/qtcompress/qzipreader.h:48:
In file included from /usr/local/lib/QtCore.framework/Headers/QFile:1:
/usr/local/lib/QtCore.framework/Headers/qfile.h:67:58: error: 'path' is unavailable: introduced in macOS 10.15
inline QString fromFilesystemPath(const std::filesystem::path &path)
                                                         ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/filesystem:909:24: note: 'path' has been explicitly marked unavailable here
class _LIBCPP_TYPE_VIS path {
                       ^
```

git bisect identified this as the bad commit on my machine:

```
# first bad commit: [e90614ea532805e6150e35351c575d4962f306c8] CMakeLists.txt changes for Qt6 compatibility - Should work with Qt5.15 and later. - Recommended: Qt5.15.2 and Qt6.2.4
```

The whole bisect log:

```
dale@unpacklo:/Users/dale/code/stellarium [(no branch, bisect started on master)]> git bisect log
git bisect start
# bad: [31d65a51659460c1646590360a52c67134492f48] Update BUILDING.md
git bisect bad 31d65a51659460c1646590360a52c67134492f48
# bad: [8be796528257b9613e7650856553c58ef18cdc5c] Solve deprecation
git bisect bad 8be796528257b9613e7650856553c58ef18cdc5c
# good: [e9ff3704251bc2b55ecca4e5b94d1196fd813299] Export data for transifex
git bisect good e9ff3704251bc2b55ecca4e5b94d1196fd813299
# good: [b954a39ffe169941ac29f620459d5d6b3ceffcec] Fixed list of languages
git bisect good b954a39ffe169941ac29f620459d5d6b3ceffcec
# good: [33b9b9c371a1100b43041220352b2a5f850baee7] Fix crash in debug mode
git bisect good 33b9b9c371a1100b43041220352b2a5f850baee7
# bad: [e90614ea532805e6150e35351c575d4962f306c8] CMakeLists.txt changes for Qt6 compatibility - Should work with Qt5.15 and later. - Recommended: Qt5.15.2 and Qt6.2.4
git bisect bad e90614ea532805e6150e35351c575d4962f306c8
# good: [bd3fb8ee8ca7f7cb059ffe577113893e5516c4c1] Refactored the method for obtaining the compiler info in the logger
git bisect good bd3fb8ee8ca7f7cb059ffe577113893e5516c4c1
# good: [96addc9a674c3872ec638d8b35338d5118e96c9d] Fixed 'Binocular Highlights' script
git bisect good 96addc9a674c3872ec638d8b35338d5118e96c9d
# first bad commit: [e90614ea532805e6150e35351c575d4962f306c8] CMakeLists.txt changes for Qt6 compatibility - Should work with Qt5.15 and later. - Recommended: Qt5.15.2 and Qt6.2.4
```

When running cmake on the bad commit, I see this warning but I do not know if it is related to the problem I am seeing:

```
dale@unpacklo:/Users/dale/code/stellarium/build/macosx [(no branch, bisect started on master)]> cmake ../..
-- Found CMake 3.23.2
-- Platform: Darwin-21.5.0 (x86_64)
-- Found Git 2.36.1
-- Building Stellarium 0.22.2-e90614e [0.22.2.24] (Mode: Release)
-- Building an OpenGL build
-- GPS: support by Qt's NMEA handling enabled.
-- GPS: could not find GPS library - GPSD query disabled!
-- Unit tests support: disabled
-- Using system-provided zlib at /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/lib/libz.tbd
-- macOS deployment target: 10.13 (x86_64)
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
CMake Warning (dev) in plugins/OnlineQueries/src/CMakeLists.txt:
  A logical block opening on the line

    /Users/dale/code/stellarium/plugins/OnlineQueries/src/CMakeLists.txt:31 (IF)

  closes on the line

    /Users/dale/code/stellarium/plugins/OnlineQueries/src/CMakeLists.txt:38 (ENDIF)

  with mis-matching arguments.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning at plugins/OnlineQueries/src/CMakeLists.txt:35 (MESSAGE):
  Qt6WebEngine and/or Qt6WebEngineWidgets not found.  If these packages exist
  for your platform, install and rerun.  Else the program will call the
  system web browser where required.


-- Found lupdate: /usr/local/bin/lupdate
-- Found lconvert: /usr/local/bin/lconvert
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/dale/code/stellarium/build/macosx
```

This is my clang version:

```
dale@unpacklo:/Users/dale/code/stellarium [(no branch, bisect started on master)]> clang++ --version
Apple clang version 13.1.6 (clang-1316.0.21.2.5)
Target: x86_64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

My qt install via homebrew is at 5.15.5:

```
dale@unpacklo:/Users/dale/code/stellarium [(no branch, bisect started on master)]> brew info qt@5
qt@5: stable 5.15.5 (bottled) [keg-only]
Cross-platform application and UI framework
https://www.qt.io/
/usr/local/Cellar/qt@5/5.15.5_1 (10,760 files, 351.1MB)
  Poured from bottle on 2022-08-03 at 14:06:42
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/qt@5.rb
License: GFDL-1.3-only and GPL-2.0-only and GPL-3.0-only and LGPL-2.1-only and LGPL-3.0-only
==> Dependencies
Build: node ✘, pkg-config ✔, python@3.10 ✔
Required: freetype ✔, glib ✔, jpeg-turbo ✔, libpng ✔, pcre2 ✔, webp ✔
==> Requirements
Build: Xcode ✔
Required: macOS >= 10.12 ✔
==> Caveats
We agreed to the Qt open source license for you.
If this is unacceptable you should uninstall.

qt@5 is keg-only, which means it was not symlinked into /usr/local,
because this is an alternate version of another formula.

If you need to have qt@5 first in your PATH, run:
  echo 'export PATH="/usr/local/opt/qt@5/bin:$PATH"' >> /Users/dale/.bash_profile

For compilers to find qt@5 you may need to set:
  export LDFLAGS="-L/usr/local/opt/qt@5/lib"
  export CPPFLAGS="-I/usr/local/opt/qt@5/include"

For pkg-config to find qt@5 you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/qt@5/lib/pkgconfig"

==> Analytics
install: 77,876 (30 days), 180,352 (90 days), 608,374 (365 days)
install-on-request: 14,250 (30 days), 28,459 (90 days), 84,584 (365 days)
build-error: 7 (30 days)
```

**Comment by gzotti** [comment]
We are just upgrading to Qt6, and apparently not all code paths work yet. I wonder how cmake could apparently find Qt6 on your machine? This message above: 

>CMake Warning at plugins/OnlineQueries/src/CMakeLists.txt:35 (MESSAGE):
  Qt6WebEngine and/or Qt6WebEngineWidgets not found.  If these packages exist
  for your platform, install and rerun.  Else the program will call the
  system web browser where required.

Also your first error is around Qt using std::filesystem::path. "introduced in macOS 10.15". Is your system up to date?

**Comment by unpacklo** [comment]
As far as I can tell, yes I'm up to date.

```
dale@unpacklo:/Users/dale/code/stellarium/build/macosx [(no branch, bisect started on master)]> sw_vers
ProductName:	macOS
ProductVersion:	12.5
BuildVersion:	21G72
```

This stackoverflow [post](https://stackoverflow.com/questions/58943032/c-build-failed-on-xcode-osx-with-multiple-errors-file-io-is-unavailable-i) seems to suggest that I need to retarget the project to use at least 10.15 or somehow get clang to accept c++17 as the language version. Is there a place in the CMakefile or makefile that would be easy to change so I can see if either of these fix the problem?

**Comment by gzotti** [comment]
Line 269 in the master CMakeFile.txt has SET(CMAKE_CXX_STANDARD 17). 

Maybe disable some plugins, esp. OnlineQueries, for now. This message around Qt6Webengine should not show up on a system where only Qt5 is available.

**Comment by unpacklo** [comment]
Hm, so it looks like there was a local problem regarding the compile error which I seemed to have gotten around, but now I have a new problem: I seem to be building for the wrong platform?

```
[ 60%] Built target stellarium_autogen
[ 60%] Linking CXX executable stellarium
ld: warning: ignoring file /usr/local/lib/QtWebEngineWidgets.framework/Versions/A/QtWebEngineWidgets, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /usr/local/lib/QtWebEngineCore.framework/Versions/A/QtWebEngineCore, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /usr/local/lib/QtWebChannel.framework/Versions/A/QtWebChannel, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /usr/local/lib/QtPrintSupport.framework/Versions/A/QtPrintSupport, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /usr/local/lib/QtQuick.framework/Versions/A/QtQuick, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /usr/local/lib/QtQmlModels.framework/Versions/A/QtQmlModels, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /usr/local/lib/QtQml.framework/Versions/A/QtQml, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /usr/local/lib/QtConcurrent.framework/Versions/A/QtConcurrent, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /usr/local/lib/QtCharts.framework/Versions/A/QtCharts, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /usr/local/lib/QtOpenGLWidgets.framework/Versions/A/QtOpenGLWidgets, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /usr/local/lib/QtOpenGL.framework/Versions/A/QtOpenGL, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /usr/local/lib/QtMultimediaWidgets.framework/Versions/A/QtMultimediaWidgets, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /usr/local/lib/QtWidgets.framework/Versions/A/QtWidgets, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /usr/local/lib/QtGui.framework/Versions/A/QtGui, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /usr/local/lib/QtMultimedia.framework/Versions/A/QtMultimedia, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /usr/local/lib/QtDBus.framework/Versions/A/QtDBus, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /usr/local/lib/QtNetwork.framework/Versions/A/QtNetwork, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /usr/local/lib/QtPositioning.framework/Versions/A/QtPositioning, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /usr/local/lib/QtSerialPort.framework/Versions/A/QtSerialPort, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /usr/local/lib/QtCore.framework/Versions/A/QtCore, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
^Cmake[2]: *** [src/stellarium] Interrupt: 2
make[1]: *** [src/CMakeFiles/stellarium.dir/all] Interrupt: 2
make: *** [all] Interrupt: 2
```

I ended up pulling master to commit 7fe13b09df4bc36d7a8a1625c49b41f595d351f7, then deleted my build directory and recreated it. Afterward, I ran cmake and built.

**Comment by unpacklo** [comment]
Here is my cmake output:

```
dale@unpacklo:/Users/dale/code/stellarium [master]> rm -rf build/
dale@unpacklo:/Users/dale/code/stellarium [master]> mkdir -p build/macos
dale@unpacklo:/Users/dale/code/stellarium [master]> cd build/macos/
dale@unpacklo:/Users/dale/code/stellarium/build/macos [master]> cmake ../..
-- Found CMake 3.23.2
-- The C compiler identification is AppleClang 13.1.6.13160021
-- The CXX compiler identification is AppleClang 13.1.6.13160021
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test HAVE_STDATOMIC
-- Performing Test HAVE_STDATOMIC - Success
-- Platform: Darwin-21.6.0 (x86_64)
-- Found Git 2.36.1
-- Building Stellarium 1.22.2-7fe13b0 (Mode: Release)
-- Found Threads: TRUE
-- Found Qt6: /usr/local/bin/qmake (found suitable version 6.3.1)
-- Found OpenGL: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/OpenGL.framework
-- Found WrapOpenGL: TRUE
-- Building an OpenGL build
-- GPS: support by Qt's NMEA handling enabled.
-- GPS: could not find GPS library - GPSD query disabled!
-- Unit tests support: disabled
-- Using system-provided zlib at /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/lib/libz.tbd
-- macOS deployment target: 11.0 (arm64;x86_64)
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
-- Found Gettext: /usr/local/bin/msgmerge (found version "0.21")
-- Found xgettext: /usr/local/bin/xgettext
-- Found lupdate: /usr/local/bin/lupdate
-- Found lconvert: /usr/local/bin/lconvert
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/dale/code/stellarium/build/macos
```

Looks like I do in fact have Qt 6 and it also looks like I'm building arm64 as well as x86_64. I'm currently using an Intel based MacBook Pro, should I disable the arm64 build?

**Comment by alex-w** [comment]
@unpacklo I see you are using x86_64 macOS, where installed x86_64-only Qt framework. You need an one extra cmake option (`-D CMAKE_OSX_ARCHITECTURES=x86_64`) in addition to `../..`.

P.S. `cmake -DCMAKE_OSX_ARCHITECTURES=x86_64 ../..`

**Comment by unpacklo** [comment]
@alex-w thanks, `cmake -DCMAKE_OSX_ARCHITECTURES=x86_64 ../..` fixed it for me!

Is it possible for the build architectures to be automatically detected in the future?

**Comment by alex-w** [comment]
Autodetect is working for Qt5.

**Comment by alex-w** [comment]
> Is it possible for the build architectures to be automatically detected in the future?

Is it possible to detect the architectures of Qt framework via cmake?

**Comment by gzotti** [comment]
https://cmake.org/cmake/help/latest/variable/CMAKE_HOST_SYSTEM_PROCESSOR.html
Maybe you have to evaluate uname -p etc.?

**Comment by alex-w** [comment]
> https://cmake.org/cmake/help/latest/variable/CMAKE_HOST_SYSTEM_PROCESSOR.html
> Maybe you have to evaluate uname -p etc.?

Nope. You are see host CPU architecture, but not an architecture of Qt framework.

**Comment by alex-w** [comment]
Ok, I found solution :)
