### ISSUE TITLE
Building Stellarium 25.1 with Qt 6.9.1, cpp 14.3 fails

### ISSUE THREAD

**Issue by dhdeangelis** [Stellarium/stellarium#4355]
### Expected Behaviour
Source code builds without errors

### Actual Behaviour
Error on 'no matching function for call' in [AngleSpinBox.cpp](https://github.com/Stellarium/stellarium/blob/master/src/gui/AngleSpinBox.cpp)

```
/usr/local/src/stellarium-25.1/src/gui/AngleSpinBox.cpp: In member function ‘virtual QSize AngleSpinBox::minimumSizeHint() const’:
/usr/local/src/stellarium-25.1/src/gui/AngleSpinBox.cpp:513:71: error: no matching function for call to ‘QString::arg(int, int, char, const int&, char)’
  512 |                                 refText = QString("%1%2d %3m %4s").arg(signPlaceholder).arg(359).arg(59)
      |                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  513 |                                                                   .arg(0, 0, 'f', decimalPlaces, ' ');
      |                                                                   ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/qt6/QtCore/qcoreapplication.h:8,
                 from /usr/include/qt6/QtGui/qguiapplication.h:8,
                 from /usr/local/src/stellarium-25.1/src/core/StelApp.hpp:25,
                 from /usr/local/src/stellarium-25.1/src/stelMain_pch.hpp:32,
                 from /usr/local/src/stellarium-25.1/build/src/CMakeFiles/stelMain.dir/cmake_pch.hxx:5,
                 from <command-line>:
```

### System
* Stellarium version: 25.1
* Operating system: openSUSE Tumbleweed 20250606
* Qt: 6.9.1
* GCC / CPP 14.3

**Comment by gzotti** [comment]
Probably something changed in Qt6.9.1. Can you build with 6.8?

**Comment by dhdeangelis** [comment]
> Probably something changed in Qt6.9.1. Can you build with 6.8?

Yes, very probably a change in Qt. I do not have 6.8 installed to try but I believe I have seen similar problems in other software. I will investigate and see how this can be solved.

**Comment by 10110111** [comment]
I think it was fixed in bbcd60ae52b6f1395ef2390a2d2ba9d0f98db548.

**Comment by dhdeangelis** [comment]
> I think it was fixed in [bbcd60a](https://github.com/Stellarium/stellarium/commit/bbcd60ae52b6f1395ef2390a2d2ba9d0f98db548).

Effectively, this is the case. I have now built Stellarium master wihtout problems. Closing this. Sorry for the noise.
