### PR TITLE
Port code to INDI 2.0.2 and update CPM

### PR DESCRIPTION
**Pull request by paolostivanin**
This PR is based on the work done by some people at https://github.com/Stellarium/stellarium/pull/2891. In particular:
* patch created by @panicgh was applied as is, since it worked fine
* the code created by @ckuethe was updated to work with v2.0 since it was not compiling

What was tested:
* compilation using the OS' INDI 2.0.2 works fine
* compilation using the CPM's INDI 2.0.2 works fine
* the TelescopeControl plugin could be loaded and connected to a INDIserver instance using Simulators.

What was **not** tested:
* connection to real hardware
* real hardware working properly

### CODE REVIEW

**Comment by gzotti** [comment]
Looks interesting, thank you! Anybody with real hardware willing to test?

**Comment by 10110111** [comment]
> the TelescopeControl plugin could be loaded and connected to a INDIserver instance using Simulators

IIRC there were some problems only present in Qt6 but not Qt5. Did you check this?

**Comment by alex-w** [comment]
macOS:
```
[  4%] Building CXX object plugins/TelescopeControl/src/INDI/CMakeFiles/TelescopeControl_INDI.dir/TelescopeControl_INDI_autogen/mocs_compilation.cpp.o
In file included from /Users/aw/stellarium/builds/macosx/plugins/TelescopeControl/src/INDI/TelescopeControl_INDI_autogen/mocs_compilation.cpp:2:
In file included from /Users/aw/stellarium/builds/macosx/plugins/TelescopeControl/src/INDI/TelescopeControl_INDI_autogen/EWIEGA46WW/moc_INDIConnection.cpp:9:
/Users/aw/stellarium/builds/macosx/plugins/TelescopeControl/src/INDI/TelescopeControl_INDI_autogen/EWIEGA46WW/../../../../../../../../plugins/TelescopeControl/src/INDI/INDIConnection.hpp:23:10: fatal error: 'libindi/baseclient.h' file not found
#include "libindi/baseclient.h"
         ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [plugins/TelescopeControl/src/INDI/CMakeFiles/TelescopeControl_INDI.dir/TelescopeControl_INDI_autogen/mocs_compilation.cpp.o] Error 1
make[1]: *** [plugins/TelescopeControl/src/INDI/CMakeFiles/TelescopeControl_INDI.dir/all] Error 2
make: *** [all] Error 2
Stellarium.app: No such file or directory

```

**Comment by paolostivanin** [comment]
@alex-w thanks for checking macos! I'm gonna look into it

**Comment by paolostivanin** [comment]
That's weird though, I can't reproduce that issue locally :thinking:

**Comment by alex-w** [comment]
> That's weird though, I can't reproduce that issue locally 🤔

Probably you have locally installed INDI

**Comment by paolostivanin** [comment]
yep I do have INDI installed, but I'm running cmake with `-DPREFER_SYSTEM_INDILIB=OFF` and cmake is executing the CPM action while generating stuff.
I'll try on a vm

**Comment by panicgh** [comment]
Thanks for following this up. I am super busy at the moment and got stuck in the CMake porting part.

I wonder if it is really necessary to build INDI through `CPMAddPackage` and then repeating parts of INDI's CMakeFile (including version, so-version, dependencies between some files etc.) and only building selected parts of INDI. Wouldn't it be simpler to either build full INDI as CMake external project or not build it at all and simply require a system-provided INDI? It appears to me that the current approach makes it unnecessarily hard to port to new INDI versions.

**Comment by paolostivanin** [comment]
I agree that bundling INDI is, IMHO, not the best solution.
I also think that we should treat INDI like any other dep: is it installed? Yes, then build the plugin. No? Then don't build the plugin.

**Comment by gzotti** [comment]
If the existence of compatible versions is guaranteed by simple dependencies, and we don't change anything in the INDI code, this would be OK for me.

**Comment by 10110111** [comment]
Wouldn't this go against the practice used for `QXlsx` and `CalcMySky`, which were also once optional but are now CPM-required?

**Comment by gzotti** [comment]
If INDI is available as standard package from default repositories just like Qt stuff, and people may have installed them already for other programs, it would be preferred over CPM and private compilations. But I had understood our first adoption of INDI had some non-standard edits in the INDI 0.* sources, so required a private build. The other packages for QXlsx and CMS are also still optional, but there are no apt packages from Debian, right?

**Comment by 10110111** [comment]
> there are no apt packages from Debian, right?

Right.

BTW I just noticed that in Ubuntu, even in 23.04 and the development version Stellarium still is 0.22.2. Do you happen to know why it's so old?

**Comment by gzotti** [comment]
No, I don't know how the official Ubuntu maintainers upgrade their packages. We provide an Ubuntu repo with the latest version, see Guide 2.3.3. If INDI does the same, it should be fine for us. But CPM may be the solution if INDI is not available everywhere.

**Comment by paolostivanin** [comment]
Hello :smile: do we have a final decision on what to do with INDI? Treat it as a dep or bundle it?

**Comment by alex-w** [comment]
INDI client within Telescope Control plugin expected to all platforms, so, e.g. Windows user can connect direct to INDI server onto Linux. The current branch has few `#include` directives to building the INDI-client, but when INDI is not installed locally, then headers are missing (INDI2 has other locations for these files) - the code of Telescope Control plugin should be updates to reflect the changes paths in INDI.

**Comment by paolostivanin** [comment]
I guess we better keep CPM then. Otherwise Windows support could be an issue :thinking: 
I'll update the PR

**Comment by gzotti** [comment]
Any news? It seems other projects are expecting Stellarium finally moving to INDI 2.* 'really soon'.

**Comment by gzotti** [comment]
Any news here?

**Comment by hmartinez82** [comment]
I'm working on getting Stellarium running on Windows on ARM. I already got it working without CalcMySky and without the Telescope plugin (due to INDI). But I just packaged CalcMySky and I'm going to package INDI, but it will have to be the latest INDI (2.0.4 as of this writing) so support for INDI 2.x should happen soon™️ .

**Comment by alex-w** [comment]
Any progress?

**Comment by hmartinez82** [comment]
Well since I got Stellarium building for Windows on Arm with the current INDI I did now pursue this any further. It was not my main objective.

 I don't know this library nor how it's used by Stellarium so someone who knows this stuff should do this upgrade

**Comment by panicgh** [comment]
As already mentioned four months ago: if we didn't try to build INDI from Stellarium but treat it like any other dependency, the issue would have been long solved. Some distros, e.g. NixOS, apply the patch for new INDI support and just use the system-provided INDI.

**Comment by gzotti** [comment]
If we can depend on optionally system-installed stock INDI2 (build yourself where required), this would be the best solution IMO. When users don't need telescope control, there is no need for INDI either. That would make it a "recommended" package for apt-get or similar systems.  We still need to know what "our own copy" has changed, and a maintainer who occasionally cares for INDI updates as years go by.

**Comment by gzotti** [comment]
- the pull request has conflicts
- From @panicgh 's wording ("we") I had expected final changes, build and usage instructions to get that working on all platforms, etc., for people not familiar with the internals of INDI. This must come from someone with a goto telescope which then must be sure to work. 
- seems too late for tomorrow's 23.4, but let's target it for 24.1

**Comment by gzotti** [comment]
Anybody using INDI and interested to move forward?

**Comment by gzotti** [comment]
Is anybody out there using Stellarium with INDI interested in going forward?
Is anybody out there on Windows using Stellarium with some INDI server on the local network? 
Is there a header package for Windows available from INDI?
Should we ask in some INDI forum for multiplatform guidance?

**Comment by carlosal1015** [comment]
Arch Linux users would like using INDI, for Windows cases I do not know.

**Comment by gzotti** [comment]
Yes, there are people who want to USE it. Are there users who want to use this part of the program and are also capable of MAKING it work? Or, given that it somehow works, still improve what's wrong with the current situation.  If INDI is unsupported in Windows (which I don't know) we can also exclude it on this platform.

**Comment by alex-w** [comment]
Tried testing on INDI mount simulator - it can be connected/disconnected, but not targeting

**Comment by alex-w** [comment]
OK, so, 4 subtasks are open at the moment: 
- restoring unit testing 
- building INDIclient in FreeBSD
- restoring speed chooser for directional movements in INDIclient
- movement of telescope circles onto sky.

**Comment by alex-w** [comment]
Well, the PR is ready to review and merge almost - I don’t understand why marker of telescope is not showed a targeting to the selected object or position. Is it problem for INDI only or for any telescope?

**Comment by alex-w** [comment]
> Well, the PR is ready to review and merge almost - I don’t understand why marker of telescope is not showed a targeting to the selected object or position. Is it problem for INDI only or for any telescope?

Hmm… I can check the problem in master with INDI 1.8.5 (why I didn’t think about this possibility before?)

**Comment by alex-w** [comment]
OK, the problem in current port of INDI
