### ISSUE TITLE
Cannot compile with Qt5.10 (Windows/Visual Studio 2015)

### ISSUE THREAD

**Issue by gzotti** [Stellarium/stellarium#139]
### Expected Behaviour

Compiles. 

### Actual Behaviour
```
[39/97 0.0/sec] Building CXX object src\CMakeFiles\stelMain.dir\core\modules\HipsMgr.cpp.obj
FAILED: src/CMakeFiles/stelMain.dir/core/modules/HipsMgr.cpp.obj 
C:\PROGRA~2\MICROS~4.0\VC\BIN\amd64\cl.exe   /nologo /TP -DCOPYRIGHT_YEARS=\"2000-2018\" -DENABLE_GPS -DENABLE_MEDIA -DENABLE_NLS -DENABLE_SCRIPT_CONSOLE -DENABLE_SPOUT -DGIT_BRANCH=\"master\" -DGIT_COMMITS=\"15915\" -DINSTALL_DATADIR=\".\" -DINSTALL_LOCALEDIR=\"./locale\" -DNDEBUG -DNOMINMAX -DPACKAGE_VERSION=\"0.90.0\" -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_GUI_LIB -DQT_MULTIMEDIAWIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_POSITIONING_LIB -DQT_PRINTSUPPORT_LIB -DQT_SCRIPT_LIB -DQT_SERIALPORT_LIB -DQT_WIDGETS_LIB -DSTELLARIUM_MAJOR=0 -DSTELLARIUM_MINOR=90 -DSTELLARIUM_PATCH=0 -DUSE_STATIC_PLUGIN_ANGLEMEASURE -DUSE_STATIC_PLUGIN_ARCHAEOLINES -DUSE_STATIC_PLUGIN_COMPASSMARKS -DUSE_STATIC_PLUGIN_EQUATIONOFTIME -DUSE_STATIC_PLUGIN_EXOPLANETS -DUSE_STATIC_PLUGIN_FOV -DUSE_STATIC_PLUGIN_METEORSHOWERS -DUSE_STATIC_PLUGIN_NAVSTARS -DUSE_STATIC_PLUGIN_NOVAE -DUSE_STATIC_PLUGIN_OBSERVABILITY -DUSE_STATIC_PLUGIN_OCULARS -DUSE_STATIC_PLUGIN_POINTERCOORDINATES -DUSE_STATIC_PLUGIN_PULSARS -DUSE_STATIC_PLUGIN_QUASARS -DUSE_STATIC_PLUGIN_REMOTECONTROL -DUSE_STATIC_PLUGIN_REMOTESYNC -DUSE_STATIC_PLUGIN_SATELLITES -DUSE_STATIC_PLUGIN_SCENERY3D -DUSE_STATIC_PLUGIN_SOLARSYSTEMEDITOR -DUSE_STATIC_PLUGIN_SUPERNOVAE -DUSE_STATIC_PLUGIN_TELESCOPECONTROL -DUSE_STATIC_PLUGIN_TEXTUSERINTERFACE -DWIN32_LEAN_AND_MEAN -D_CRT_SECURE_NO_WARNINGS -D_USE_MATH_DEFINES -Isrc -IC:\Stellarium_DEV\GIT\stellarium\src -I. -IC:\Stellarium_DEV\GIT\stellarium\src\core -IC:\Stellarium_DEV\GIT\stellarium\src\core\modules -IC:\Stellarium_DEV\GIT\stellarium\src\core\planetsephems -IC:\Stellarium_DEV\GIT\stellarium\src\gui -IC:\Stellarium_DEV\GIT\stellarium\src\scripting -IC:\Stellarium_DEV\GIT\stellarium\src\external\zlib -IC:\Stellarium_DEV\GIT\stellarium\src\external\qtcompress -IC:\Qt\Qt5.10.0\5.10.0\msvc2015_64\include -IC:\Qt\Qt5.10.0\5.10.0\msvc2015_64\include\QtCore -IC:\Qt\Qt5.10.0\5.10.0\msvc2015_64\.\mkspecs\win32-msvc -IC:\Stellarium_DEV\GIT\stellarium\src\external\glues_stel\source -IC:\Qt\Qt5.10.0\5.10.0\msvc2015_64\include\QtGui -IC:\Qt\Qt5.10.0\5.10.0\msvc2015_64\include\QtANGLE -IC:\Qt\Qt5.10.0\5.10.0\msvc2015_64\include\QtPrintSupport -IC:\Qt\Qt5.10.0\5.10.0\msvc2015_64\include\QtWidgets -IC:\Qt\Qt5.10.0\5.10.0\msvc2015_64\include\QtNetwork -IC:\Stellarium_DEV\GIT\stellarium\plugins\RemoteControl\src\..\include -IC:\Qt\Qt5.10.0\5.10.0\msvc2015_64\include\QtConcurrent -IC:\Qt\Qt5.10.0\5.10.0\msvc2015_64\include\QtSerialPort -IC:\Stellarium_DEV\GIT\stellarium\plugins\TelescopeControl\src\INDI -IC:\Stellarium_DEV\GIT\stellarium\src\external\libindi -IC:\Stellarium_DEV\GIT\stellarium\src\external\libindi\libs -IC:\Qt\Qt5.10.0\5.10.0\msvc2015_64\include\QtMultimedia -IC:\Qt\Qt5.10.0\5.10.0\msvc2015_64\include\QtMultimediaWidgets -IC:\Qt\Qt5.10.0\5.10.0\msvc2015_64\include\QtScript -IC:\Qt\Qt5.10.0\5.10.0\msvc2015_64\include\QtPositioning /DWIN32 /D_WINDOWS /W3 /GR /EHsc /wd4244 /wd4305 /wd4351 /wd4996 /MD /O2 /Ob2 /D NDEBUG /showIncludes /Fosrc\CMakeFiles\stelMain.dir\core\modules\HipsMgr.cpp.obj /Fdsrc\CMakeFiles\stelMain.dir\ /FS -c C:\Stellarium_DEV\GIT\stellarium\src\core\modules\HipsMgr.cpp
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\type_traits(1434): error C2672: 'std::invoke': no matching overloaded function found
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\functional(208): note: see reference to function template instantiation 'void std::_Invoke_ret<_Rx,_Callable&,const QVector<Vec3d>&,const QVector<Vec2f>&,const QVector<uint16_t>&>(std::_Forced<_Rx,true>,_Callable &,const QVector<Vec3d> &,const QVector<Vec2f> &,const QVector<uint16_t> &)' being compiled
        with
        [
            _Rx=void,
            _Callable=_Decayed
        ]
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\functional(206): note: while compiling class template member function 'void std::_Func_impl<_Decayed,_Alloc,_Ret,const QVector<Vec3d> &,const QVector<Vec2f> &,const QVector<uint16_t> &>::_Do_call(const QVector<Vec3d> &,const QVector<Vec2f> &,const QVector<uint16_t> &)'
        with
        [
            _Alloc=std::allocator<int>,
            _Ret=void
        ]
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\functional(134): note: see reference to class template instantiation 'std::_Func_impl<_Decayed,_Alloc,_Ret,const QVector<Vec3d> &,const QVector<Vec2f> &,const QVector<uint16_t> &>' being compiled
        with
        [
            _Alloc=std::allocator<int>,
            _Ret=void
        ]
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\functional(337): note: see reference to class template instantiation 'std::_Is_large<_Myimpl>' being compiled
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\functional(316): note: see reference to function template instantiation 'void std::_Func_class<_Ret,const QVector<Vec3d> &,const QVector<Vec2f> &,const QVector<uint16_t> &>::_Reset_alloc<_Ty,std::allocator<_Ty>>(_Fx &&,const _Alloc &)' being compiled
        with
        [
            _Ret=void,
            _Ty=int,
            _Fx=int,
            _Alloc=std::allocator<int>
        ]
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\functional(316): note: see reference to function template instantiation 'void std::_Func_class<_Ret,const QVector<Vec3d> &,const QVector<Vec2f> &,const QVector<uint16_t> &>::_Reset_alloc<_Ty,std::allocator<_Ty>>(_Fx &&,const _Alloc &)' being compiled
        with
        [
            _Ret=void,
            _Ty=int,
            _Fx=int,
            _Alloc=std::allocator<int>
        ]
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\functional(482): note: see reference to function template instantiation 'void std::_Func_class<_Ret,const QVector<Vec3d> &,const QVector<Vec2f> &,const QVector<uint16_t> &>::_Reset<int>(_Fx &&)' being compiled
        with
        [
            _Ret=void,
            _Fx=int
        ]
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\functional(482): note: see reference to function template instantiation 'void std::_Func_class<_Ret,const QVector<Vec3d> &,const QVector<Vec2f> &,const QVector<uint16_t> &>::_Reset<int>(_Fx &&)' being compiled
        with
        [
            _Ret=void,
            _Fx=int
        ]
C:\Stellarium_DEV\GIT\stellarium\src\core\StelHips.hpp(80): note: see reference to function template instantiation 'std::function<void (const QVector<Vec3d> &,const QVector<Vec2f> &,const QVector<uint16_t> &)>::function<int>(_Fx)' being compiled
        with
        [
            _Fx=int
        ]
C:\Stellarium_DEV\GIT\stellarium\src\core\modules\HipsMgr.cpp(153): note: see reference to function template instantiation 'std::function<void (const QVector<Vec3d> &,const QVector<Vec2f> &,const QVector<uint16_t> &)>::function<int>(_Fx)' being compiled
        with
        [
            _Fx=int
        ]
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\type_traits(1434): error C2893: Failed to specialize function template 'unknown-type std::invoke(_Callable &&,_Types &&...)'
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\type_traits(1434): note: With the following template arguments:
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\type_traits(1434): note: '_Callable=_Decayed &'
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\type_traits(1434): note: '_Types={const QVector<Vec3d> &, const QVector<Vec2f> &, const QVector<uint16_t> &}'
```

### Steps to reproduce
Use Qt5.10/MSVC2015. Not tried with Qt5.10 on other platforms.

Note that it works on Qt5.9/MSVC2015. 

### System
* Operating system: Windows 7
* MSVC 2015
* Qt5.10

What's missing here?

**Comment by 10110111** [comment]
`NULL` might have been replaced by an `int` value somewhere after upgrade... Try replacing it with `nullptr` in `StelHips.hpp:80`.

**Comment by gzotti** [comment]
Thanks, yes. Sometimes I'm blind...
